# Generated by Django 5.1.2 on 2025-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, to='core.equipamento'),
        ),
    ]
