# Generated by Django 5.1.2 on 2025-07-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario_equipamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ConteudoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('descricao', models.TextField(blank=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modeloequipamento')),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='modelos_equipamento',
            field=models.ManyToManyField(blank=True, to='core.modeloequipamento'),
        ),
    ]
