# Generated by Django 5.1.2 on 2025-07-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modeloequipamento_alter_perfilusuario_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='role',
        ),
    ]
