# Generated by Django 5.1.2 on 2025-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_perfilusuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sessao_ativa',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
