# Generated by Django 5.1.2 on 2025-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
