# Generated by Django 5.1.2 on 2025-07-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_modulo_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='modulo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
