# Generated by Django 5.1.2 on 2025-07-08 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cursos', '0004_progressomodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='equipamento',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
            preserve_default=False,
        ),
    ]
