# Generated by Django 5.1.2 on 2025-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_modulo_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_modulos/'),
        ),
    ]
