# Generated by Django 5.1.2 on 2025-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_modulo_imagem_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='beneficios',
            field=models.TextField(blank=True, default=''),
        ),
    ]
