# Generated by Django 5.1.2 on 2025-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_certificadoemitido_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoemitido',
            name='numero_certificado',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
